name: "Generate GitHub Apps token"

on:
  workflow_call:
    outputs:
      token:
        description: Generated GitHub Apps token
        value: ${{ jobs.generate-github-apps-token.outputs.token }}

jobs:
  generate-github-apps-token:
    runs-on: ubuntu-latest
    env:
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    outputs:
      token: ${{ steps.generate.outputs.token }}
    steps:
      - id: generate
        run: ./generate-github-apps-token.sh
        working-directory: scripts
